apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: test-cicd
spec:
  podTemplate: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'MoOyeg/gitops-repo')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: ci-dryrun-from-push
    template:
      name: ci-dryrun-from-push-template
  - bindings:
    - ref: test-dev-app-taxi-taxi-binding
    - ref: github-push-binding
    interceptors:
    - github:
        secretRef:
          secretKey: webhook-secret-key
          secretName: webhook-secret-test-dev-taxi
    - cel:
        filter: (header.match('X-GitHub-Event', 'push') && body.repository.full_name == 'MoOyeg/taxi')
        overlays:
        - expression: body.ref.split('/')[2]
          key: ref
    name: app-ci-build-from-push-taxi
    template:
      name: app-ci-template
status:
  configuration:
    generatedName: ""
