apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  name: gitops-webhook-event-listener-route
  namespace: test-cicd
spec:
  host: ""
  ports:
    - name: http-listener
      protocol: TCP
      port: 8080
      targetPort: 8000
  to:
    kind: Service
    name: el-cicd-event-listener
    weight: 100
  wildcardPolicy: None
